on:
  workflow_call:

jobs:
  pubish_unit_tests:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    - name: Download Junit Artifact
        id: download_junit
        uses: actions/download-artifact@v3
        with:
          name: junit
          path: test-results/junit

    - name: Download Clover Artifact
        id: download_clover
        uses: actions/download-artifact@v3
        with:
          name: clover
          path: coverage/clover.xml

    steps:
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Unit Test Results"
          files: test-results/junit/results.xml

      - name: Coverage Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: "coverage/clover.xml"
          min-line-coverage: 20
          min-method-coverage: 20
