name: "[Workflow] Release"

on:
  release:
    types: [released]

jobs:
  create_changelog_commit:
    name: Create and commit Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        token: ${{ secrets.PAT }}

    - name: Update Changelog
      uses: stefanzweifel/changelog-updater-action@v1.12.0
      with:
        latest-version: ${{ github.event.release.tag_name }}
        release-notes: ${{ github.event.release.body }}

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'

    - name: Cache yarn dependencies
      id: cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build Module
      run: yarn run build
    
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      run: |
        jq --arg version "${{ github.event.release.tag_name }}" \
          --arg url "https://github.com/${{ github.repository }}" \
          --arg manifest "https://github.com/${{ github.repository }}/releases/latest/download/module.json" \
          --arg download "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip" \
          '.version = $version | .url = $url | .manifest = $manifest | .download = $download' \
          module.json > module.tmp.json && mv module.tmp.json module.json

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ./module.zip module.json CHANGELOG.md LICENSE dist/ styles/ languages/ templates/ packs/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./module.zip'
        body: ${{ github.event.release.body }}
        allowUpdates: true

    - name: Commit updated CHANGELOG
      uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
      with:
        branch: ${{ github.event.release.target_commitish }}
        commit_message: Update CHANGELOG
        file_pattern: CHANGELOG.md
